# Generated by Django 5.0 on 2025-11-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_challenge_created_at_course_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="created_at",
        ),
    ]
