# Generated by Django 5.0 on 2025-11-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_module_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="created_at",
        ),
    ]
