# Generated by Django 5.0 on 2025-11-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_module_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={"ordering": ("-enrolled_at",)},
        ),
        migrations.AlterModelOptions(
            name="userchallengeattempt",
            options={"ordering": ("-submitted_at",)},
        ),
        migrations.AddField(
            model_name="challenge",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="mastery",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="module",
            name="skill_tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userchallengeattempt",
            name="time_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="module",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
