# Generated by Django 5.1.4 on 2025-11-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_enrollment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challenge",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="challenge",
            name="command_to_practice",
            field=models.CharField(
                blank=True,
                help_text="The specific command learners should practice",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="evaluation_type",
            field=models.CharField(
                choices=[
                    ("exact", "Exact Output Match"),
                    ("contains", "Output Contains"),
                    ("command", "Command Executed"),
                    ("file_exists", "File/Directory Exists"),
                ],
                default="contains",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="challenge",
            name="setup_commands",
            field=models.TextField(
                blank=True,
                help_text="Commands to set up the environment (one per line)",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="theory_content",
            field=models.TextField(
                blank=True, help_text="Educational content explaining the concept"
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="visualization_script",
            field=models.TextField(
                blank=True, help_text="Commands to run for visualization/demo"
            ),
        ),
    ]
